<a href="https://colab.research.google.com/github/kimeunh3/Intro_to_Tensorflow/blob/main/%EC%8B%A4%EC%8A%B55_%ED%9E%88%EB%93%A0%EB%A0%88%EC%9D%B4%EC%96%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 히든레이어
 - 보스턴 집값 예측: ['https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'](https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv)
 - 아이리스 품종 분류: ['https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'](https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv)

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 보스턴 집값 예측

In [17]:
# 1. 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

# 독립변수, 종속변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 
          'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [18]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [19]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [22]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 18.3896
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 17.5469
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 16.9601
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 19.6168
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 16.9866
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 18.5608
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 19.0937
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 17.8204
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 18.0966
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 18.1608


In [23]:
# 4. 모델을 이용합니다.
print(model.predict(독립[:5]))
print(종속[:5])

[[29.828133]
 [25.704052]
 [34.449596]
 [35.518044]
 [34.62385 ]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


# 아이리스 품종 분류

In [25]:
# 1. 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)

# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']] 
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [27]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [32]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0780 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0799 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0847 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0770 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0742 - accuracy: 0.9667
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0790 - accuracy: 0.9600
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0772 - accuracy: 0.9667
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0763 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0754 - accuracy: 0.9667
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0790 - accuracy: 0.9600


In [34]:
# 4. 모델을 이용합니다.
print(model.predict(독립[-5:]))
print(종속[-5:])

[[1.7564440e-10 9.4090858e-03 9.9059087e-01]
 [1.4055725e-09 1.4018092e-02 9.8598194e-01]
 [7.3105890e-09 6.6363767e-02 9.3363625e-01]
 [3.0752276e-09 3.8895249e-02 9.6110475e-01]
 [2.5500771e-07 2.7132502e-01 7.2867471e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1
