<a href="https://colab.research.google.com/github/kimeunh3/Intro_to_Tensorflow/blob/main/%EC%8B%A4%EC%8A%B53_%EC%95%84%EC%9D%B4%EB%A6%AC%EC%8A%A4_%ED%92%88%EC%A2%85_%EB%B6%84%EB%A5%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 아이리스 품종 분류
 - github csv url: ['https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'](https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv)

In [2]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [3]:
# 1. 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head() 

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [4]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [5]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [6]:
# 독립변수, 종속변수를 분리합니다.
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [7]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [16]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2217 - accuracy: 0.9667
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2207 - accuracy: 0.9667
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2205 - accuracy: 0.9667
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2202 - accuracy: 0.9600
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2200 - accuracy: 0.9667
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2200 - accuracy: 0.9600
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2195 - accuracy: 0.9667
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2194 - accuracy: 0.9600
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2190 - accuracy: 0.9667
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2189 - accuracy: 0.9667
Epoch 11/100
5/5 [===========

In [17]:
# 4. 모델을 이용합니다.
model.predict(독립[0:5])

array([[9.9687469e-01, 3.1212135e-03, 4.0529121e-06],
       [9.9095446e-01, 9.0265851e-03, 1.8843219e-05],
       [9.9500620e-01, 4.9840631e-03, 9.7036327e-06],
       [9.8713118e-01, 1.2837982e-02, 3.0875130e-05],
       [9.9723685e-01, 2.7595367e-03, 3.5320161e-06]], dtype=float32)

In [18]:
print(종속[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [19]:
model.predict(독립[-5:])

array([[1.2604512e-05, 9.1559224e-02, 9.0842813e-01],
       [2.3724537e-05, 2.1603130e-01, 7.8394496e-01],
       [3.2351520e-05, 2.1849400e-01, 7.8147358e-01],
       [8.9118794e-06, 8.4985867e-02, 9.1500527e-01],
       [4.9936061e-05, 3.0536789e-01, 6.9458216e-01]], dtype=float32)

In [21]:
print(종속[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [22]:
# 학습한 가중치
model.get_weights()

[array([[ 0.5206791 , -0.12260296, -0.69792455],
        [ 1.9496357 ,  0.07113015, -0.64827114],
        [-3.4971735 ,  0.0124726 ,  0.4215465 ],
        [-2.3797207 , -1.7080855 ,  2.0764883 ]], dtype=float32),
 array([ 1.8392073 ,  0.88048065, -1.6436342 ], dtype=float32)]